### ISSUE TITLE
Swagger docs over HTTPS

### ISSUE THREAD

**Issue by jasonrig** [mytardis/mytardis#562] opened 2015-11-25 00:06 UTC
Just testing PR #561. Looks fine, but behaves badly over https.
If you try to look at any of the options for the endpoints listed, the JS console in Chrome dev tools will say something like:

```
Mixed Content: The page at 'https://118.138.236.219/api/v1/swagger/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://118.138.236.219/api/v1/swagger/schema/user'. This request has been blocked; the content must be served over HTTPS.
```

**Comment by grischa** [comment] 2015-11-25 00:07
@pansapiens

**Comment by pansapiens** [comment] 2015-11-25 00:47
Ah - well spotted. It looks like others have hit this issue recently (currently unresolved: https://github.com/concentricsky/django-tastypie-swagger/issues/107)

If it's easy for you to test, could you try setting SECURE_PROXY_SSL_HEADER in Django settings, as per: https://github.com/concentricsky/django-tastypie-swagger/issues/48 ?

**Comment by jasonrig** [comment] 2015-11-25 00:48
Will do. I'll get back to you shortly with the result.

**Comment by jasonrig** [comment] 2015-11-25 02:30
Problem solved by adding `proxy_set_header X-Forwarded-Proto $scheme;` to nginx config. `proxy_set_header X-Forwarded-Protocol $scheme;` was already there though... I've added both as it seems that different browsers respect one or the other unpredictably.

https://code.djangoproject.com/ticket/14597 mentions:
"... headers X-Forwarded-Protocol and X-Forwarded-Ssl (refered to HTTPS headers hereafter) are not part of any official standards, but are being used as a convention. Besides there are implementations that use other similar names. X-Forwarded-Proto are Front-End-Https are some of them."

**Comment by wettenhj** [comment] 2015-11-28 02:35
Happy for this to have been merged.  I just wanted to make a note that when talking about whether you are using "X-Forwarded-Proto" or "X-Forwarded-Protocol" in your Nginx config, it's important to also mention which one you have in your MyTardis settings.py / settings.pickle / settings.changeme.  In my experience, this header just needs to be consistent(*) between MyTardis (Django) and Nginx.

(*) The requirement for matching between settings.py and Nginx is not case sensitive, and it's normal to see underscores in settings.py but hyphens in Nginx config, and it's normal to see the "HTTP_" prefix in settings.py but not in Nginx config, e.g. you can have this in settings.py:

```SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')```

and this in your Nginx config:
```
    location / {
        proxy_set_header X-Forwarded-Proto $scheme;
```

Underscores in headers are disabled by default in Nginx: http://nginx.org/en/docs/http/ngx_http_core_module.html#underscores_in_headers

**Comment by grischa** [comment] 2015-12-01 06:46
Does this need docs then, @wettenhj @pansapiens @jasonrig ?

**Comment by wettenhj** [comment] 2018-07-23 05:50
Duplicate of https://github.com/mytardis/mytardis/issues/1127

**Closed by wettenhj** 2018-07-23 05:50 UTC
